$Version=2$
egvapi "application/http"
    {
    // Auth Params (mostly defaults):
    "VancoWS.Auth.RequestType" "http/parameter" {type=string; source=none; usage=post; default="EFTCustomerInfo";}
    //Note: the ID is only hashed to provide a semi-unique value. It is not crucial for it to be totally unique, nor does it need to be secure
    "VancoWS.Auth.RequestID" "http/parameter" {type="string"; source="none"; usage="post"; default=runserver( (hash("md5", convert("string", getdate()))) );} 
    "VancoWS.Auth.RequestTime" "http/parameter" {type="string"; source="none"; usage="post"; default= runserver( (convert("string", getdate())) );} 
    "VancoWS.Auth.SessionID" "http/parameter" {type="string"; source="param"; usage="post"; default="";}
    "VancoWS.Auth.Version" "http/parameter" {type="string"; source="none"; usage="post"; default="2";} 
    
    // Request Params
    "VancoWS.Request.RequestVars.CustomerRef" "http/parameter" {type=string; source=param; usage=post;} 
    "VancoWS.Request.RequestVars.ClientID" "http/parameter" {type=string; source=none; usage=post; default=runserver( (select first(:a_config_value) from /apps/kardia/data/Kardia_DB/a_config/rows where :a_config_name = 'VP_Client') );} 

    // Connection information -- https://myvanco.vancopayments.com/cgi-bin/ws2.vps
    server = "myvanco.vancopayments.com";
    path = "/cgi-bin/ws2.vps";
    protocol = "https";
    method = POST;
    allowsubdirs = 0;
    cache_max_ttl = 86400000;
    cache_min_ttl = 3600000;
    request_content_type =  "application/xml";
    expected_content_charset = "iso-8859-1";
    override_content_charset = "true";
    }
